# permissions for end users to edit networkpolicyrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkpolicyrule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: segmentation
    app.kubernetes.io/part-of: segmentation
    app.kubernetes.io/managed-by: kustomize
  name: networkpolicyrule-editor-role
rules:
- apiGroups:
  - microsegmentation.security.io
  resources:
  - networkpolicyrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microsegmentation.security.io
  resources:
  - networkpolicyrules/status
  verbs:
  - get
